# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76b840e6dea0db1d8785be71034b3eb2f8eb42845344aa9847cfa4d6f86deea4daed81f7477425ef7664fce9dcc85574289e95af96162a9afb2de46a080c1c39

test:
  secret_key_base: c73c225885993e37956c683996160541df7a5685e33b7af60fd5c2e7baa918903ffb59fd0b2809fcad5edc569f3ca0240305d6dbb3a155831c72dd88a62c6c9f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
